TUNING = GLOBAL.TUNING

TUNING.DYM = 
{
	ROOM_PLAIN = GetModConfigData("room_percent_plain"),
	ROOM_FOREST = GetModConfigData("room_percent_forest"),
	ROOM_SAVANNA = GetModConfigData("room_percent_savanna"),
	ROOM_MARSH = GetModConfigData("room_percent_marsh"),
	ROOM_ROCKY = GetModConfigData("room_percent_rocky"),
	ROOM_DECIDUOUSFOREST = GetModConfigData("room_percent_deciduous"),
	ROOM_DESERT = GetModConfigData("room_percent_desert"),
	ROOM_MOONISLAND = GetModConfigData("room_percent_moonisland"),
	--ROOM_SINKHOLE = GetModConfigData("room_percent_sinkhole"),
	--ROOM_MUD = GetModConfigData("room_percent_mud"),
	
	ROOM_GRASS = GetModConfigData("room_prefab_grass"),
	ROOM_SAPLING = GetModConfigData("room_prefab_sapling"),
	ROOM_BERRYBUSH = GetModConfigData("room_prefab_berrybush"),
	ROOM_CARROT = GetModConfigData("room_prefab_carrot"),
	ROOM_FLOWER = GetModConfigData("room_prefab_flower"),
	ROOM_REEDS = GetModConfigData("room_prefab_reeds"),
	ROOM_MARSHBUSH = GetModConfigData("room_prefab_marshbush"),
	ROOM_MUSHROOM = GetModConfigData("room_prefab_mushroom"),
	ROOM_CACTUS = GetModConfigData("room_prefab_cactus"),
	ROOM_EVERGREEN = GetModConfigData("room_prefab_evergreen"),
	ROOM_DECIDUOUS = GetModConfigData("room_prefab_deciduoustree"),
	ROOM_MARSHTREE = GetModConfigData("room_prefab_marshtree"),
	ROOM_POND = GetModConfigData("room_prefab_pond"),
	ROOM_POND2 = GetModConfigData("room_prefab_pond2"),
	ROOM_ROCK1 = GetModConfigData("room_prefab_rock1"),
	ROOM_ROCK2 = GetModConfigData("room_prefab_rock2"),
	ROOM_FLINT = GetModConfigData("room_prefab_flint"),
	ROOM_PIGHOUSE = GetModConfigData("room_prefab_pighouse"),
	ROOM_MERMHOUSE = GetModConfigData("room_prefab_mermhouse"),
	ROOM_BEEHIVE = GetModConfigData("room_prefab_beehive"),
	ROOM_SPIDERDEN = GetModConfigData("room_prefab_spiderden"),
	ROOM_HOUNDMOUND = GetModConfigData("room_prefab_houndmound"),
	ROOM_TENTACLE = GetModConfigData("room_prefab_tentacle"),
	ROOM_TUMBLEWEED = GetModConfigData("room_prefab_tumbleweed"),
	ROOM_FIREFLIES = GetModConfigData("room_prefab_fireflies"),
	--caves for next update
	--ROOM_CAVELIGHT = GetModConfigData("room_prefab_cavelight"),
	--ROOM_LIGHTFLOWER = GetModConfigData("room_prefab_lightflower"),
}